### ISSUE TITLE
sampling.strategies doesn't work in all in one image version 1.6

### ISSUE THREAD

**Issue by Yisaer** [jaegertracing/jaeger-kubernetes#101]
Hi, I'm using `all-in-one`  docker image version 1.6 and i want to discard some certain services by setting sampling strategies.  Here was my `configration` and i found that jaeger still trace `istio-mixer` and `istio-policy` services.

```
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: istio-tracing
  labels:
    jaeger-infra: istio-tracing
data:
  config.json: |-
    {
      "service_strategies": [
        {
          "service": "istio-mixer",
          "type": "const",
          "param": 0
        },
        {
          "service": "istio-policy",
          "type": "const",
          "param": 0
        },
        {
            "service": "istio-telemetry",
            "type": "const",
            "param": 0
        }
      ]
    }
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: istio-tracing
  namespace: istio-system
  labels:
    app: istio-tracing
    chart: tracing-0.1.0
    release: istio
    heritage: Tiller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jaeger
      annotations:
        sidecar.istio.io/inject: "false"
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: istio-tracing
      containers:
        - name: jaeger
          image: "docker.io/jaegertracing/all-in-one:1.6"
          imagePullPolicy: IfNotPresent
          args:
            - '--sampling.strategies-file=/etc/conf/config.json'
          ports:
            - containerPort: 9411
            - containerPort: 16686
            - containerPort: 5775
              protocol: UDP
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
          volumeMounts:
          - name: config-volume
            mountPath: /etc/conf
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: COLLECTOR_ZIPKIN_HTTP_PORT
            value: "9411"
          - name: MEMORY_MAX_TRACES
            value: "50000"
          livenessProbe:
            initialDelaySeconds: 360
            httpGet:
              path: /
              port: 16686
          readinessProbe:
            initialDelaySeconds: 360
            httpGet:
              path: /
              port: 16686
          resources:
            requests:
              cpu: 10m
            
      affinity:      
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - ppc64le
          - weight: 2
            preference:
              matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - s390x




```
