### ISSUE TITLE
how to add my application service to jaeger 

### ISSUE THREAD

**Issue by splnanthakumar** [jaegertracing/jaeger-kubernetes#107]
i have installed jaeger which is mentioned in git
```
core@logan-1-coreos-378 ~ $ kubectl create -f https://raw.githubusercontent.com/jaegertracing/jaeger-kubernetes/master/all-in-one/jaeger-all-in-one-template.yml -n jaeger
deployment.extensions "jaeger-deployment" created
service "jaeger-query" created
service "jaeger-collector" created
service "jaeger-agent" created
service "zipkin" created
core@logan-1-coreos-378 ~ $ kubectl get svc -n jaeger
NAME               TYPE           CLUSTER-IP   EXTERNAL-IP   PORT(S)                               AGE
jaeger-agent       ClusterIP      None         <none>        5775/UDP,6831/UDP,6832/UDP,5778/TCP   12s
jaeger-collector   ClusterIP      10.3.3.216   <none>        14267/TCP,14268/TCP,9411/TCP          12s
jaeger-query       LoadBalancer   10.3.3.255   <pending>     80:7359/TCP                           12s
zipkin             ClusterIP      None         <none>        9411/TCP                              12s
```
able to see one pod is running
```
core@logan-1-coreos-378 ~ $ kubectl get pods --all-namespaces | grep jaeger
jaeger                jaeger-deployment-5bd9f6d7ff-qj7wk                                1/1       Running   0          5m
```
but my request is not being captured in traces

i did portforwarding 10.3.3.255 . but services shows only 1 "jaeger-query"

Questions:
1. Is there any other config to add my application services to jaeger?

few logs says that as follows:
```
orders-signup-uwsgi-deployment-66fbb77bd-8ckbr jaeger-agent {"level":"info","ts":1540558760.5167942,"caller":"peerlistmgr/peer_list_mgr.go:166","msg":"Trying to connect to peer","host:port":"jaeger-collector.jaeger-infra.svc:14267"}
orders-signup-uwsgi-deployment-66fbb77bd-8ckbr jaeger-agent {"level":"error","ts":1540558760.5441663,"caller":"peerlistmgr/peer_list_mgr.go:171","msg":"Unable to connect","host:port":"jaeger-collector.jaeger-infra.svc:14267","connCheckTimeout":0.25,"error":"dial tcp: lookup jaeger-collector.jaeger-infra.svc on 10.3.0.10:53: no such host","stacktrace":"github.com/jaegertracing/jaeger/pkg/discovery/peerlistmgr.(*PeerListManager).ensureConnections\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/pkg/discovery/peerlistmgr/peer_list_mgr.go:171\ngithub.com/jaegertracing/jaeger/pkg/discovery/peerlistmgr.(*PeerListManager).maintainConnections\n\t/home/travis/gopath/src/github.com/jaegertracing/jaeger/pkg/discovery/peerlistmgr/peer_list_mgr.go:101"}
```

**Comment by pavolloffay** [comment]
@splnanthakumar hi. The app you want to trace has to be instrumented  for example using OpenTracing instrumentation and it has to use jaeger client configured to send data to jaeger server. 

I will close this as it is not issue related to k8s deployment.

**Comment by jpkrohling** [comment]
@splnanthakumar looks like you installed Jaeger in the `jaeger` namespace (`-n jaeger`), but configured your agent to connect to a collector under the `jaeger-infra` namespace (`jaeger-collector.jaeger-infra.svc`).

Try changing the agent to not mention the `namespace.svc` part, referencing only the service name (`jaeger`).

If you still have problems, let us know in our Gitter room: https://gitter.im/jaegertracing/Lobby

**Comment by splnanthakumar** [comment]
i have installed jaeger on my default namesapce called "central"
```
core@logan-1-coreos-378 ~ $ kubectl get svc -n central | grep jaeger
jaeger-agent                      ClusterIP      None          <none>        5775/UDP,6831/UDP,6832/UDP,5778/TCP                 4h
jaeger-collector                  ClusterIP      10.3.12.102   <none>        14267/TCP,14268/TCP,9411/TCP                        4h
jaeger-query                      LoadBalancer   10.3.12.51    <pending>     80:30082/TCP                                        4h
core@logan-1-coreos-378 ~ $
```

**Comment by splnanthakumar** [comment]
the following is the prometheus details :

```
core@logan-1-coreos-378 ~ $ kubectl get all | grep prome
pod/prometheus-68bcf489c7-httjh                                       1/1       Running   0          3h


service/prometheus                        LoadBalancer   10.3.11.209   <pending>     9090:30900/TCP                                      3h

deployment.apps/prometheus                                           1         1         1            1           3h

replicaset.apps/prometheus-68bcf489c7                                           1         1         1         3h
core@logan-1-coreos-378 ~ $
```

**Comment by splnanthakumar** [comment]
here is my deployment yaml file:

```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels: {appid: b6752f625351, groupid: default, orders-app: orders-signup,
    version: 2.9.5-37}
  name: orders-signup-uwsgi-deployment
  namespace: orders
spec:
  replicas: 1
  selector:
    matchLabels: {orders-app: orders-signup}
  template:
    metadata:
      labels: {orders-app: orders-signup, version: 2.9.5-37}
    spec:
      containers:
      - args: [orders-signup]
        image: *******/global_signup:2.9.5-37
        imagePullPolicy: IfNotPresent
        name: orders-signup
        ports:
        - {containerPort: 10143}
        resources:
          limits: {memory: 750Mi}
          requests: {memory: 750Mi}
        env:
        - name: JAEGER_AGENT_HOST
          value: "10.3.12.51"
      hostAliases:
      - hostnames: [foo.local, bar.local]
        ip: 127.0.0.1
      - hostnames: [logan-1-coreos-378.test.pdt1]
        ip: 15.184.16.202
      imagePullSecrets:
      - {name: ****}
```
