### ISSUE TITLE
Agent sidecar resources defined in README. 

### ISSUE THREAD

**Issue by astub** [jaegertracing/jaeger-kubernetes#59]
Not really sure how much resources a sidecar needs. Is 128Mi too much?
```yaml
resources:
  limits:
    memory: 128Mi
  requests:
    memory: 128Mi
```
