### ISSUE TITLE
Documenting sender configuration

### ISSUE THREAD

**Issue by objectiser** [jaegertracing/jaeger-kubernetes#6]
When trying out the template with a simple example service, I needed to use the following config to get the service reporting spans to the server:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example-app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-app 
        image: <YOUR IMAGE/VERSION>
        ports:
        - name: web
          containerPort: 8080
        env:
          - name: JAEGER_SERVICE_NAME
            value: <YOUR SERVICE NAME>
          - name: JAEGER_AGENT_HOST
            value: jaeger-all-in-one-agent
          - name: JAEGER_SAMPLER_TYPE
            value: const
          - name: JAEGER_SAMPLER_PARAM
            value: "1"
```

This example uses the [Jaeger TracerResolver](https://github.com/uber/jaeger-client-java/tree/master/jaeger-tracerresolver), but the tracer could be directly configured using the same information - the main issue was setting the UDP sender's host name to `jaeger-all-in-one-agent`.

Wonder where best to record this info - should we add it to the README?
