### ISSUE TITLE
Ingress Configuration

### ISSUE THREAD

**Issue by Spellchaser** [jaegertracing/jaeger-kubernetes#94]
While trying to expose jaeger to a custom base-path, I was running into odd errors. Stuff like can't load resources, everything redirecting to the main landing page with no results, and http parsing errors. 

It turns out for some other services, we had the annotation `ingress.kubernetes.io/rewrite-target` set to `/` which threw off all the requests. 

So if anyone else searches/runs into this problem without understanding ingresses, the default ingress works.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jaeger-ingress
spec:
  rules:
  - http:
      paths:
      - path: /jaeger
        backend:
          serviceName: jaeger-query
          servicePort: 80
```

You don't want a rewrite-target
```
metadata:
  annotations:
    ingress.kubernetes.io/rewrite-target: /
  name: main-ingress
```
it'll output errors like 
```
Uncaught SyntaxError: Unexpected token < jaeger:1
Uncaught SyntaxError: Unexpected token < main.4f0c2202.js:1
Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://....com/jaeger/static/css/main.160e898e.css". jaeger:10
```

As far as I can tell it's because the k8s ingress doesn't [play nice](https://github.com/kubernetes/ingress-nginx/issues/1755) with angular

**Comment by Spellchaser** [comment]
I wasn't sure where to stick it. 
I'm don't think many users will encounter this, so adding this to main landing page would make it more cluttered and make things more confusing imo.

**Comment by jpkrohling** [comment]
I'll close this one, as it it indeed doesn't seem like it would belong to the website. If more users face this specific issue in the future, we could add your finding to a possible "troubleshooting" section.

**Comment by cushind** [comment]
I had the same error for a different reason when using a custom base path.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
    kubernetes.io/ingress.class: traefik
  name: jaegertracing-ingress
  namespace: monitoring
spec:
  rules:
  - host: myhost
    http:
      paths:
      - path: /jaeger
        backend:
          serviceName: jaeger-query
          servicePort: 80
```

This wasn't working because I was still using `PathPrefixStrip`. Removing this annotation fixed the issue for me.
